### ISSUE TITLE
Wrong name of FatFS folder

### ISSUE THREAD

**Issue by vbolshakov** [grblHAL/STM32F1xx#1]
There is STM32CubeIDE warning:
Description	Resource	Path	Location	Type
Invalid project path: Missing project folder or file: \GRBL Driver STM32F103C8\FatFS for Source path.	GRBL Driver STM32F103C8		pathentry	Path Entry Problem

Can be solved by renaming FatFs to FatFS.

**Comment by terjeio** [comment]
Thanks, another mistake masked by Windows... The correct name is FatFs, but I've seen other variants from MCU vendors. I will update the .project file to use FatFs in the next update.
