### ISSUE TITLE
Support for variety of Mach3 boards based on STM32F1XX

### ISSUE THREAD

**Issue by beastieboy** [grblHAL/STM32F1xx#15]
There are many STM32F1 based boards made for Mach3 that can be reprogrammed with grblHAL firmware. Currently I have this one:

[DDMACH V5.0](https://sc04.alicdn.com/kf/Ua101434f1d1945afaafc246f897f9ed9J.jpg)

It's based on STM32F105VCT6. Where to begin with? I can easily trace pinout.

**Comment by terjeio** [comment]
> Where to begin with? I can easily trace pinout.

Creating a pin map file would be a good starting point. Then sort out the clock tree configuration. I usually create a processor specific project to verify the USB connection and then copy the clock tree setup from that to the grblHAL driver - I have done so many times for the [STM32F4xx driver.](https://github.com/grblHAL/STM32F4xx/blob/1c8cfaccd3cb45752a5233028086adab79f55178/Src/main.c#L50-L228)

**Comment by beastieboy** [comment]
Here are the photos taken together:

![IMG_1167 (1)](https://user-images.githubusercontent.com/10076537/157311884-b85f3359-ff81-4a69-b22f-879e4365e1a0.jpeg)
![Ua101434f1d1945afaafc246f897f9ed9J](https://user-images.githubusercontent.com/10076537/157312006-5681a1ab-16e6-465f-a050-b98bb8004404.jpeg)
<img width="940" alt="STM32F105" src="https://user-images.githubusercontent.com/10076537/157312086-cda6a907-2f58-464b-81e6-6fafa75a05c3.png">

**Comment by terjeio** [comment]
Did you manage to create a map file?
