### ISSUE TITLE
SKR MINI E3 V2.0 Unable to Invert Direction

### ISSUE THREAD

**Issue by NeoKurtex** [grblHAL/STM32F1xx#25]
I recently set up GRBLHAL on a SKR Mini E3 V2.0 board and i am having issues inverting the step directions of an axis. Changing the values of $3 don't have any effect. Is there another way of inverting the axis direction or does this need to be done through physical wiring?

**Comment by terjeio** [comment]
Another bug - only affecting the SKR Mini. So try again...

**Comment by NeoKurtex** [comment]
yep, works now. Thanks!
