### ISSUE TITLE
The latest firmware cannot be used in OpenBuilds and UGS

### ISSUE THREAD

**Issue by adepacarmerah** [grblHAL/STM32F1xx#52]
hello terje, 3 months ago I installed stm32 bluepill and it can run normally on openbuilds controller and UGS, now with the latest firmware it can't use openbuilds or ugs, even I want to change the settings in io sender it can't save, there is a bus I can get the firmware version  longer?

**Comment by terjeio** [comment]
> now with the latest firmware it can't use openbuilds or ugs

The version commited yesterday? Post your `$I` output please.

> there is a bus I can get the firmware version longer?

This does not make any sense for me.

Are you compiling locally on your own machine or are you using the Web Builder?
