### ISSUE TITLE
can't compile for stm32 F1XX web builder

### ISSUE THREAD

**Issue by adepacarmerah** [grblHAL/STM32F1xx#59]
Hi Terje, for the past 2 days I have not been able to compile grblhal stm32f1xx for cnc 3040 via web builder, it says build failed

**Comment by terjeio** [comment]
Hmm, the compiler used by the Web Builder does not optimize as well as the one used by the STM32CubeIDE so the flash overflows. Either I have to remove Web Builder support for the cnc3040 or I'll have to remove functionality, possibly the canned cycle gcodes?

**Comment by Jamilgalau** [comment]
remove some rarely used functions, the important thing is to be solid to do GRBL work, because this board is easy to get and provides a low cost controller option

**Comment by terjeio** [comment]
The Web Builder has been updated, I stripped out a bunch of pin names so it should compile for a while longer.
