### ISSUE TITLE
GRBLHAL Compatibility option

### ISSUE THREAD

**Issue by FusionHolic** [grblHAL/STM32F1xx#60]
hello terje i am impressed with grblhal and it works very well with bluepill, i want to use full grbl compatibility, does this mean grbl performance is the same as grbl arduino basic, or does it have performance improvements like grblhal? because i don't need features like tool replacement or complex systems

**Comment by terjeio** [comment]
It has the same performance improvements in all (compatibility) modes.

**Comment by FusionHolic** [comment]
Ok thx terje..great project
