### ISSUE TITLE
Compilation failed for TRINAMIC_ENABLE 2209 + TRINAMIC_DEV 1

### ISSUE THREAD

**Issue by AndWalu** [grblHAL/STM32F1xx#8]
Errors:
'reg_ptr' undeclared (first use in this function)	trinamic.c	/GRBL Driver STM32F103C8/motors	line 774
'reg_ptr' undeclared (first use in this function)	trinamic.c	/GRBL Driver STM32F103C8/motors	line 874
'stepper[report.sg_status_motor]' is a pointer; did you mean to use '->'?	trinamic.c	/GRBL Driver STM32F103C8/motors	line 690
'tmc5160_regaddr_t' undeclared (first use in this function)	trinamic.c	/GRBL Driver STM32F103C8/motors	line 774
expected ')' before 'gc_block'	trinamic.c	/GRBL Driver STM32F103C8/motors	line 774	C/C++ Problem

**Comment by terjeio** [comment]
I have missed this in between all the emails I have in my inbox, sorry for that.

This driver do not have lowlevel support for TMC2209, either hardware or software UARTs has to be added for that depending on which board it is to be used for. Easiest will be hardware UART if a single port is used to communicate with the drivers.
